<?php

/**
 * PluginsbSessionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsbSessionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsbSessionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsbSession');
    }
}