<?php

/**
 * PluginSessionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSessionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSessionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSession');
    }
}