all:
  storage:
    class: sfPDOSessionStorage
    param:
      db_table:    sb_session      # Name of the table storing the sessions
      database:    doctrine        # Name of the database connection to use
      # Optional parameters
      db_id_col:   id              # Name of the column storing the session id
      db_data_col: session_data    # Name of the column storing the session data
      db_time_col: time            # Name of the column storing the session timestamp
